[workspace]
members = [
    "crates/manowar",
    "programs/identity",
    "programs/reputation",
    "programs/validation",
    "programs/market",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
borsh = { version = "1.5", features = ["derive"] }
manowar = { path = "crates/manowar" }
solana-program = "2"
